-- begin DDCPC_POWER_CONSTRAINT
alter table DDCPC_POWER_CONSTRAINT add constraint FK_DDCPC_POWER_CONSTRAINT_ON_CONSTRAINT foreign key (CONSTRAINT_ID) references SEC_CONSTRAINT(ID)^
alter table DDCPC_POWER_CONSTRAINT add constraint FK_DDCPC_POWER_CONSTRAINT_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table DDCPC_POWER_CONSTRAINT add constraint FK_DDCPC_POWER_CONSTRAINT_ON_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID)^
create index IDX_DDCPC_POWER_CONSTRAINT_ON_CONSTRAINT on DDCPC_POWER_CONSTRAINT (CONSTRAINT_ID)^
create index IDX_DDCPC_POWER_CONSTRAINT_ON_USER on DDCPC_POWER_CONSTRAINT (USER_ID)^
create index IDX_DDCPC_POWER_CONSTRAINT_ON_ROLE on DDCPC_POWER_CONSTRAINT (ROLE_ID)^
-- end DDCPC_POWER_CONSTRAINT
